services:
  palm-beach-cannes-strapi:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - palm-beach-cannes-network
      - dokploy-network
    # expose:
    #   - 1337
    ports:
      - 1337
    labels:
      - traefik.enable=true
      - traefik.http.routers.next-app.rule=Host(`next-app.dokploy.com`)
      - traefik.http.routers.next-app.entrypoints=websecure
      - traefik.http.routers.next-app.tls.certResolver=letsencrypt
      - traefik.http.services.next-app.loadbalancer.server.port=3000
    depends_on:
      - palm-beach-cannes-db

  palm-beach-cannes-db:
    image: postgres:14.0-alpine
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - palm-beach-cannes-data:/var/lib/postgresql/data/ #using a volume
    networks:
      - palm-beach-cannes-network
      - dokploy-network
    expose:
      - 5432

volumes:
  palm-beach-cannes-data:
    name: palm-beach-cannes-data

networks:
  palm-beach-cannes-network:
    name: palm-beach-cannes-network
  dokploy-network:
    external: true
