// Interface automatically generated by schemas-to-ts

import { ImageLink } from '../components/elements/ImageLink';
import { Link } from '../components/elements/Link';
import { ImageLink_Plain } from '../components/elements/ImageLink';
import { Link_Plain } from '../components/elements/Link';
import { ImageLink_NoRelations } from '../components/elements/ImageLink';
import { Link_NoRelations } from '../components/elements/Link';

export interface Footer {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logo?: ImageLink;
    text?: any;
    socialLinks: ImageLink[];
    linksTitle?: string;
    links: Link[];
    newsletterTitle?: string;
    policyLinks: Link[];
    locale: string;
    localizations?: { data: Footer[] };
  };
}
export interface Footer_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo?: ImageLink_Plain;
  text?: any;
  socialLinks: ImageLink_Plain[];
  linksTitle?: string;
  links: Link_Plain[];
  newsletterTitle?: string;
  policyLinks: Link_Plain[];
  locale: string;
  localizations?: Footer_Plain[];
}

export interface Footer_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo?: ImageLink_NoRelations;
  text?: any;
  socialLinks: ImageLink_NoRelations[];
  linksTitle?: string;
  links: Link_NoRelations[];
  newsletterTitle?: string;
  policyLinks: Link_NoRelations[];
  locale: string;
  localizations?: Footer[];
}

export interface Footer_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logo?: ImageLink_Plain;
  text?: any;
  socialLinks: ImageLink_Plain[];
  linksTitle?: string;
  links: Link_Plain[];
  newsletterTitle?: string;
  policyLinks: Link_Plain[];
  locale: string;
  localizations?: Footer[];
}
