// Interface automatically generated by schemas-to-ts

import { ImageLink } from '../components/elements/ImageLink';
import { ImageLink_Plain } from '../components/elements/ImageLink';
import { ImageLink_NoRelations } from '../components/elements/ImageLink';

export interface Header {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    logoTransparent?: ImageLink;
    logo?: ImageLink;
    linksLeft?: any;
    linksRight?: any;
    locale: string;
    localizations?: { data: Header[] };
  };
}
export interface Header_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoTransparent?: ImageLink_Plain;
  logo?: ImageLink_Plain;
  linksLeft?: any;
  linksRight?: any;
  locale: string;
  localizations?: Header_Plain[];
}

export interface Header_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoTransparent?: ImageLink_NoRelations;
  logo?: ImageLink_NoRelations;
  linksLeft?: any;
  linksRight?: any;
  locale: string;
  localizations?: Header[];
}

export interface Header_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  logoTransparent?: ImageLink_Plain;
  logo?: ImageLink_Plain;
  linksLeft?: any;
  linksRight?: any;
  locale: string;
  localizations?: Header[];
}
