// Interface automatically generated by schemas-to-ts

import { ImageLink } from './ImageLink';
import { ImageLink_Plain } from './ImageLink';
import { ImageLink_NoRelations } from './ImageLink';

export interface DropdownLink {
  text?: string;
  link: ImageLink[];
}
export interface DropdownLink_Plain {
  text?: string;
  link: ImageLink_Plain[];
}

export interface DropdownLink_NoRelations {
  text?: string;
  link: ImageLink_NoRelations[];
}

