// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Image } from './Image';
import { Link_Plain } from './Link';
import { Image_Plain } from './Image';
import { Link_NoRelations } from './Link';
import { Image_NoRelations } from './Image';

export interface ImageLink {
  internalTitle?: string;
  link?: Link;
  image?: Image;
}
export interface ImageLink_Plain {
  internalTitle?: string;
  link?: Link_Plain;
  image?: Image_Plain;
}

export interface ImageLink_NoRelations {
  internalTitle?: string;
  link?: Link_NoRelations;
  image?: Image_NoRelations;
}

