// Interface automatically generated by schemas-to-ts

import { Image } from './Image';
import { Image_Plain } from './Image';
import { Image_NoRelations } from './Image';

export interface ImageTextTitle {
  image?: Image;
  title?: string;
  text?: any;
}
export interface ImageTextTitle_Plain {
  image?: Image_Plain;
  title?: string;
  text?: any;
}

export interface ImageTextTitle_NoRelations {
  image?: Image_NoRelations;
  title?: string;
  text?: any;
}

