// Interface automatically generated by schemas-to-ts

import { Link } from './Link';
import { Multimedia } from './Multimedia';
import { Link_Plain } from './Link';
import { Multimedia_Plain } from './Multimedia';
import { Link_NoRelations } from './Link';
import { Multimedia_NoRelations } from './Multimedia';

export interface LinkMultimediaTextTitle {
  title?: string;
  text?: any;
  link?: Link;
  multimedia?: Multimedia;
}
export interface LinkMultimediaTextTitle_Plain {
  title?: string;
  text?: any;
  link?: Link_Plain;
  multimedia?: Multimedia_Plain;
}

export interface LinkMultimediaTextTitle_NoRelations {
  title?: string;
  text?: any;
  link?: Link_NoRelations;
  multimedia?: Multimedia_NoRelations;
}

