// Interface automatically generated by schemas-to-ts

import { Multimedia } from './Multimedia';
import { Multimedia_Plain } from './Multimedia';
import { Multimedia_NoRelations } from './Multimedia';

export interface MultimediaText {
  internalTitle?: string;
  text?: any;
  multimedia?: Multimedia;
}
export interface MultimediaText_Plain {
  internalTitle?: string;
  text?: any;
  multimedia?: Multimedia_Plain;
}

export interface MultimediaText_NoRelations {
  internalTitle?: string;
  text?: any;
  multimedia?: Multimedia_NoRelations;
}

