// Interface automatically generated by schemas-to-ts

export interface TextTextTitle {
  title?: string;
  text1?: any;
  text2?: any;
}
export interface TextTextTitle_Plain {
  title?: string;
  text1?: any;
  text2?: any;
}

export interface TextTextTitle_NoRelations {
  title?: string;
  text1?: any;
  text2?: any;
}

