// Interface automatically generated by schemas-to-ts

export interface Text {
  internalTitle?: string;
  text?: any;
}
export interface Text_Plain {
  internalTitle?: string;
  text?: any;
}

export interface Text_NoRelations {
  internalTitle?: string;
  text?: any;
}

