// Interface automatically generated by schemas-to-ts

import { Image } from '../elements/Image';
import { Multimedia } from '../elements/Multimedia';
import { Image_Plain } from '../elements/Image';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Image_NoRelations } from '../elements/Image';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Content_03 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  text?: any;
  logo?: Image;
  multimedia?: Multimedia;
}
export interface Content_03_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  text?: any;
  logo?: Image_Plain;
  multimedia?: Multimedia_Plain;
}

export interface Content_03_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  text?: any;
  logo?: Image_NoRelations;
  multimedia?: Multimedia_NoRelations;
}

