// Interface automatically generated by schemas-to-ts

import { MultimediaText } from '../elements/MultimediaText';
import { MultimediaText_Plain } from '../elements/MultimediaText';
import { MultimediaText_NoRelations } from '../elements/MultimediaText';

export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Content_02 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  textMultimedia?: MultimediaText;
}
export interface Content_02_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  textMultimedia?: MultimediaText_Plain;
}

export interface Content_02_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  textMultimedia?: MultimediaText_NoRelations;
}

