// Interface automatically generated by schemas-to-ts

import { LinkMultimediaTextTitle } from '../elements/LinkMultimediaTextTitle';
import { LinkMultimediaTextTitle_Plain } from '../elements/LinkMultimediaTextTitle';
import { LinkMultimediaTextTitle_NoRelations } from '../elements/LinkMultimediaTextTitle';

export enum SectionTitleColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum CardsTextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum CardsBackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Content_04 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  cardsTextColor?: CardsTextColor;
  cardsBackgroundColor?: CardsBackgroundColor;
  sectionTitle?: string;
  text?: any;
  cards?: LinkMultimediaTextTitle;
}
export interface Content_04_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  cardsTextColor?: CardsTextColor;
  cardsBackgroundColor?: CardsBackgroundColor;
  sectionTitle?: string;
  text?: any;
  cards?: LinkMultimediaTextTitle_Plain;
}

export interface Content_04_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  cardsTextColor?: CardsTextColor;
  cardsBackgroundColor?: CardsBackgroundColor;
  sectionTitle?: string;
  text?: any;
  cards?: LinkMultimediaTextTitle_NoRelations;
}

