// Interface automatically generated by schemas-to-ts

import { Multimedia } from '../elements/Multimedia';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Content_01 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  text?: any;
  multimedia?: Multimedia;
}
export interface Content_01_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  text?: any;
  multimedia?: Multimedia_Plain;
}

export interface Content_01_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  reverseColumnsOrder?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  text?: any;
  multimedia?: Multimedia_NoRelations;
}

