// Interface automatically generated by schemas-to-ts

import { MultimediaText } from '../elements/MultimediaText';
import { MultimediaText_Plain } from '../elements/MultimediaText';
import { MultimediaText_NoRelations } from '../elements/MultimediaText';

export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum CardsTextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum CardsBackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Grid_01 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  backgroundColor?: BackgroundColor;
  cardsTextColor?: CardsTextColor;
  cardsBackgroundColor?: CardsBackgroundColor;
  card: MultimediaText[];
}
export interface Grid_01_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  backgroundColor?: BackgroundColor;
  cardsTextColor?: CardsTextColor;
  cardsBackgroundColor?: CardsBackgroundColor;
  card: MultimediaText_Plain[];
}

export interface Grid_01_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  backgroundColor?: BackgroundColor;
  cardsTextColor?: CardsTextColor;
  cardsBackgroundColor?: CardsBackgroundColor;
  card: MultimediaText_NoRelations[];
}

