// Interface automatically generated by schemas-to-ts

import { Link } from '../elements/Link';
import { Multimedia } from '../elements/Multimedia';
import { Link_Plain } from '../elements/Link';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Link_NoRelations } from '../elements/Link';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Hero_01 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  text?: any;
  link?: Link;
  multimedia?: Multimedia;
}
export interface Hero_01_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  text?: any;
  link?: Link_Plain;
  multimedia?: Multimedia_Plain;
}

export interface Hero_01_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  text?: any;
  link?: Link_NoRelations;
  multimedia?: Multimedia_NoRelations;
}

