// Interface automatically generated by schemas-to-ts

import { Multimedia } from '../elements/Multimedia';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export interface Media_02 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  multimedia?: Multimedia;
}
export interface Media_02_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  multimedia?: Multimedia_Plain;
}

export interface Media_02_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  multimedia?: Multimedia_NoRelations;
}

