// Interface automatically generated by schemas-to-ts

import { Link } from '../elements/Link';
import { Multimedia } from '../elements/Multimedia';
import { Link_Plain } from '../elements/Link';
import { Multimedia_Plain } from '../elements/Multimedia';
import { Link_NoRelations } from '../elements/Link';
import { Multimedia_NoRelations } from '../elements/Multimedia';

export enum LinkColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Media_03 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  linkColor?: LinkColor;
  link?: Link;
  multimedia?: Multimedia;
}
export interface Media_03_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  linkColor?: LinkColor;
  link?: Link_Plain;
  multimedia?: Multimedia_Plain;
}

export interface Media_03_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  linkColor?: LinkColor;
  link?: Link_NoRelations;
  multimedia?: Multimedia_NoRelations;
}

