// Interface automatically generated by schemas-to-ts

export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Spacer {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  pxDesktop?: number;
  pxMobile?: number;
  backgroundColor?: BackgroundColor;
}
export interface Spacer_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  pxDesktop?: number;
  pxMobile?: number;
  backgroundColor?: BackgroundColor;
}

export interface Spacer_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  pxDesktop?: number;
  pxMobile?: number;
  backgroundColor?: BackgroundColor;
}

