// Interface automatically generated by schemas-to-ts

import { TextTextTitle } from '../elements/TextTextTitle';
import { TextTextTitle_Plain } from '../elements/TextTextTitle';
import { TextTextTitle_NoRelations } from '../elements/TextTextTitle';

export enum SectionTitleColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Text_03 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  sectionTitle?: string;
  texts: TextTextTitle[];
}
export interface Text_03_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  sectionTitle?: string;
  texts: TextTextTitle_Plain[];
}

export interface Text_03_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  sectionTitle?: string;
  texts: TextTextTitle_NoRelations[];
}

