// Interface automatically generated by schemas-to-ts

import { Text } from '../elements/Text';
import { Text_Plain } from '../elements/Text';
import { Text_NoRelations } from '../elements/Text';

export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Text_02 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  texts: Text[];
}
export interface Text_02_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  texts: Text_Plain[];
}

export interface Text_02_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  texts: Text_NoRelations[];
}

