// Interface automatically generated by schemas-to-ts

import { ImageTextTitle } from '../elements/ImageTextTitle';
import { ImageTextTitle_Plain } from '../elements/ImageTextTitle';
import { ImageTextTitle_NoRelations } from '../elements/ImageTextTitle';

export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Text_04 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  iconsTexts: ImageTextTitle[];
}
export interface Text_04_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  iconsTexts: ImageTextTitle_Plain[];
}

export interface Text_04_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  iconsTexts: ImageTextTitle_NoRelations[];
}

