// Interface automatically generated by schemas-to-ts

import { Image } from '../elements/Image';
import { Link } from '../elements/Link';
import { Image_Plain } from '../elements/Image';
import { Link_Plain } from '../elements/Link';
import { Image_NoRelations } from '../elements/Image';
import { Link_NoRelations } from '../elements/Link';

export enum Alignment {
  Left = 'Left',
  Center = 'Center',
  Right = 'Right',}
export enum SectionTitleColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum TextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}
export enum BackgroundColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface Text_01 {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  alignment?: Alignment;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  icon?: Image;
  sectionTitle?: string;
  text?: any;
  link?: Link;
}
export interface Text_01_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  alignment?: Alignment;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  icon?: Image_Plain;
  sectionTitle?: string;
  text?: any;
  link?: Link_Plain;
}

export interface Text_01_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  alignment?: Alignment;
  sectionTitleColor?: SectionTitleColor;
  textColor?: TextColor;
  backgroundColor?: BackgroundColor;
  icon?: Image_NoRelations;
  sectionTitle?: string;
  text?: any;
  link?: Link_NoRelations;
}

