// Interface automatically generated by schemas-to-ts

export enum CardsTextColor {
  Green = 'Green',
  LightGreen = 'Light green',
  Yellow = 'Yellow',
  Black = 'Black',
  Orange = 'Orange',}

export interface VenuesSlider {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cardsTextColor?: CardsTextColor;
}
export interface VenuesSlider_Plain {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cardsTextColor?: CardsTextColor;
}

export interface VenuesSlider_NoRelations {
  internalTitle?: string;
  blockId?: string;
  hide?: boolean;
  cardsTextColor?: CardsTextColor;
}

